### ISSUE TITLE
Where is docker files content?

### ISSUE THREAD

**Issue by omidraha** [testdrivenio/flask-vue-kubernetes#2]
Hi,
Where is content of docker file for these images:

[ mjhea0/vue-kubernetes](https://hub.docker.com/r/mjhea0/vue-kubernetes/)
[mjhea0/flask-kubernetes](https://hub.docker.com/r/mjhea0/flask-kubernetes/)

Thanks.

**Comment by omidraha** [comment]
I found them. 
https://github.com/testdrivenio/flask-vue-kubernetes/blob/master/services/server/dockerfile
https://github.com/testdrivenio/flask-vue-kubernetes/blob/master/services/client/Dockerfile

**Comment by guitarmanvt** [comment]
This project does not work on Linux after a clean checkout. `docker-compose build` fails to find the Dockerfiles.

This is likely because the files are committed in lowercase (`dockerfile`), but specified in titlecase (`Dockerfile`) in docker-compose.yml. While this may actually work on both Windows and Mac OS, it fails on Linux (and on filesystems that care about case, such as ext4, which you can mount in Mac, too).

Workaround: rename the files locally to `Dockerfile` (title case).

Perhaps I'll fork this and bring a PR some day.
